name: E2E tests - Playwright
on:
  pull_request:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      matrix: ${{ steps.resolve-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve Grafana E2E versions
        id: resolve-versions
        uses: grafana/plugin-actions/e2e-version@main
        with:
          version-resolver-type: version-support-policy

  playwright-tests:
    needs: setup-matrix
    timeout-minutes: 60
    strategy:
      matrix:
        GRAFANA_VERSION: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    name: E2E Tests - Grafana@${{ matrix.GRAFANA_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Copy auth file
      #   run: mkdir -p packages/plugin-e2e/playwright/.auth/ && cp .github/user.json packages/plugin-e2e/playwright/.auth/user.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Install yarn dependencies
        run: yarn install
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Build binaries
        run: mage -v build:linux

      - name: Build frontend
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start Grafana
        run: docker run --rm -d -p 3000:3000 --name=grafana --volume ./packages/plugin-e2e/provisioning:/etc/grafana/provisioning --env GOOGLE_JWT_FILE=${{secrets.GOOGLE_JWT_FILE}} --env grafana/grafana:${{ matrix.GRAFANA_VERSION }}; sleep 30

      - name: Run Playwright tests
        run: npm run playwright:test --w @grafana/plugin-e2e
        env:
          GOOGLE_JWT_FILE: ${{ secrets.GOOGLE_JWT_FILE }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-Grafana${{ matrix.GRAFANA_VERSION }}
          path: packages/plugin-e2e/playwright-report/
          retention-days: 30
